name: SkyFight
version: '1.0'
main: com.naotenhorgb.skyFight.SkyFight
authors: [ naotenhorgb ]
description: Plugin
load: POSTWORLD
commands:
  setspawn:
    permission: skyfight.admin
    description: "Seta spawn."
  setup:
    permission: skyfight.admin
    description: "Inicia o setup de set."
  build:
    permission: skyfight.buildcommand
    description: "Entra no modo de build. Fique isento dos checks ingame"
  lobby:
    permission: skyfight.default
    description: "Muda de estado para outro lugar"
  sendstatus:
    permission: skyfight.default
    description: "Envia o status"